# GWatch 监控工具配置文件
redis:
  addr: "172.235.216.169:6379"
  password: ""
  db: 0
  timeout: 5s
  pool_size: 5
  min_idle_conns: 1
  max_idle_conns: 3

dingtalk:
  webhook_url: "https://oapi.dingtalk.com/robot/send?access_token=bfd9580e7d49a959e986c7438bfa014ddb694b7b1a695fab1b46c7010b06ebad"
  secret: "SEC0b0f0a3d4f43d1d21d0a66d0d4dbd6b5c16450266d49aadbae66d12fe97b22fa"
  at_mobiles: ["19******502"]

monitor:
  interval: 3s
  cpu_threshold: 80.0
  memory_threshold: 70.0
  disk_threshold: 80.0
  redis_min_clients: 0
  redis_max_clients: 10
  alert_interval: 2m
  http_error_threshold: 0  # HTTP接口异常数量阈值
  alert_title: "香港视频化服务器告警"
  http_interfaces:
    - name: "vms-public-captcha"
      url: "https://vms.kumshingapps.com/prod-api/captchaImage"
      need_alert: true
      timeout: 10s
      allowed_codes: [200, 201, 204]
    - name: "vms-private-captcha"
      url: "http://172.235.216.169:7080/captchaImage"
      need_alert: false
      timeout: 10s
      allowed_codes: [200, 201, 204]

log:
  debug: true

javaAppDumpScript:
  path: /home/youxihu/hk_video/createJavaMapDump.sh