# GWatch 监控工具配置文件
redis:
  addr: "172.235.216.169:6379"
  password: ""
  db: 0
  timeout: 5s
  pool_size: 5
  min_idle_conns: 1
  max_idle_conns: 3

dingtalk:
  webhook_url: "https://oapi.dingtalk.com/robot/send?access_token=bfd9580e7d49a959e986c7438bfa014ddb694b7b1a695fab1b46c7010b06ebad"
  secret: "SEC0b0f0a3d4f43d1d21d0a66d0d4dbd6b5c16450266d49aadbae66d12fe97b22fa"
  at_mobiles: ["19******502"]

monitor:
  interval: 5s  # 监控间隔
  consecutive_threshold: 3  # 连续触发次数阈值
  cpu_threshold: 80.0  # CPU使用率阈值
  memory_threshold: 70.0  # 内存使用率阈值
  disk_threshold: 80.0  # 磁盘使用率阈值
  redis_min_clients: 0  # Redis最小连接数
  redis_max_clients: 10  # Redis最大连接数
  alert_interval: 2m  # 告警间隔
  alert_title: "香港视频化服务器告警"  # 告警标题 用于钉钉告警
  http_error_threshold: 0  # HTTP接口异常数量阈值
  http_interval: 10s   #http接口检查间隔
  http_interfaces: #http接口检查配置
    # - name: "vms-public-captcha"
    #   url: "https://vms.kumshingapps.com/prod-api/captchaImage"
    #   need_alert: true
    #   timeout: 3s
    #   allowed_codes: [200, 201, 204]
    # - name: "vms-private-captcha"
    #   url: "http://172.235.216.169:7080/captchaImage"
    #   need_alert: false
    #   timeout: 3s
    #   allowed_codes: [200, 201, 204]
    - name: "example-captcha"
      url: "http://172.25.216.169:7080/captchaImage"
      need_alert: false
      timeout: 3s
      allowed_codes: [200, 201, 204]

tickers:
  alert_title: "视频设备状态定时报告"  # 报告标题 用于钉钉报告
  http_interfaces:
    - name: "number of monitoring devices"
      url: "https://vms.kumshingapps.com/prod-api/api/device/query/getDDCTree"
      auth_backdoor: "123456"
      authorization: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6IjQ3MWVmYmQwLWY4NmUtNGQ3Yi04MTZhLTljY2E5ZDg5Zjk4YyJ9.-OtqDUDW5kE7dXRp4v6Pc5W87EhwRrApCL0tDL6AQCXrfUteWqXg-gf5qx17bdKO34f2KI17sJ16viatzxkEMA"
      alert_time: ["8:00", "10:00", "13:00", "13:00"]
log:
  mode: zap
  level: info
  output: logs/gwatch.log


javaAppDumpScript:
  path: /home/youxihu/hk_video/createJavaMapDump.sh