# GWatch 监控工具配置文件 - 新版本（按分类配置）
# 注释掉某个分类，该分类的所有监控都不会执行

# 主机类监控配置 - 启用
host_monitoring:
  interval: 5s  # 监控间隔
  consecutive_threshold: 3  # 连续触发次数阈值
  alert_interval: 2m  # 告警间隔
  alert_title: "香港视频化主服务器告警"  # 告警标题

  # CPU监控阈值
  cpu_threshold: 80.0

  # 内存监控阈值
  memory_threshold: 70.0

  # 磁盘监控阈值
  disk_threshold: 80.0

  # Java堆转储脚本
  javaAppDumpScript:
    path: /home/youxihu/hk_video/createJavaMapDump.sh

# 应用层类监控配置 - 启用
app_monitoring:
#  Redis监控配置
  redis:
    addr: "192.168.1.218:6379"
    password: "ningzaichun"
    db: 0
    timeout: 5s
    pool_size: 5
    min_idle_conns: 1
    max_idle_conns: 3
    min_clients: 0    # Redis最小连接数
    max_clients: 10   # Redis最大连接数

  # # MySQL监控配置 - 测试环境优化
  # mysql:
  #   host: "192.168.1.218"
  #   port: 21806
  #   username: "youxihu"
  #   password: "youxihu"
  #   database: "information_schema"
  #   timeout: 10s
  #   interval: 60s     # MySQL监控间隔（测试环境降低频率）

  #   # 连接与会话监控阈值 - 测试环境宽松设置
  #   connection_thresholds:
  #     max_connections_warning: 90    # 连接数告警阈值（百分比）- 测试环境放宽
  #     active_threads_warning: 100   # 活跃线程数告警阈值 - 测试环境放宽
  #     connection_errors_warning: 50  # 连接错误数告警阈值 - 测试环境放宽
  #     aborted_connects_warning: 20  # 中断连接数告警阈值 - 测试环境放宽

  #   # 查询性能监控阈值 - 测试环境宽松设置
  #   query_thresholds:
  #     qps_warning: 5000             # QPS告警阈值 - 测试环境放宽
  #     tps_warning: 500              # TPS告警阈值 - 测试环境放宽
  #     slow_queries_warning: 50      # 慢查询数告警阈值 - 测试环境放宽
  #     p95_response_time: 5000       # P95响应时间告警阈值（毫秒）- 测试环境放宽
  #     p99_response_time: 10000      # P99响应时间告警阈值（毫秒）- 测试环境放宽

  #   # InnoDB Buffer Pool监控阈值 - 测试环境宽松设置
  #   buffer_pool_thresholds:
  #     hit_rate_warning: 80.0        # 命中率告警阈值（百分比）- 测试环境放宽
  #     usage_warning: 95.0           # 使用率告警阈值（百分比）- 测试环境放宽

  #   # 复制状态监控（主从架构）- 测试环境禁用
  #   replication:
  #     enabled: false                # 测试环境禁用复制监控
  #     delay_warning_seconds: 300    # 复制延迟告警阈值（秒）- 测试环境放宽
  #     check_gtid: false             # 测试环境禁用GTID检查

  #   # 锁与阻塞监控阈值 - 测试环境宽松设置
  #   lock_thresholds:
  #     row_lock_waits_warning: 500   # 行锁等待次数告警阈值 - 测试环境放宽
  #     row_lock_time_warning: 5000   # 行锁等待时间告警阈值（毫秒）- 测试环境放宽
  #     deadlocks_warning: 20         # 死锁次数告警阈值 - 测试环境放宽

  #   # 事务与日志监控阈值 - 测试环境宽松设置
  #   transaction_thresholds:
  #     uncommitted_transactions_warning: 50  # 未提交事务数告警阈值 - 测试环境放宽
  #     binlog_growth_rate_warning: 500       # Binlog增长速率告警阈值（MB/小时）- 测试环境放宽
  # HTTP接口监控配置
  http:
    error_threshold: 0  # HTTP接口异常数量阈值
    interval: 10s       # HTTP接口检查间隔
    interfaces:
      - name: "example-public-captcha"
        url: "https://example.example.com/prod-api/captchaImage"
        need_alert: true
        timeout: 10s
        allowed_codes: [ 200, 201, 204 ]
      - name: "example-example-captcha"
        url: "http://172.25.216.169:7080/captchaImage"
        need_alert: false
        timeout: 10s
        allowed_codes: [ 200, 201, 204 ]
#
#  # 定时器监控配置
#  tickers:
#    ticker_title: "视频设备状态定时报告"
#    ticker_interfaces:
#      - name: "number of monitoring devices"
#        device_url: "https://example.example.com/prod-api/api/device/query/getDDCTree"
#        alert_time: ["8:00", "10:00", "13:00", "16:00"]
#        auth:
#          mode: "static"
#          static_token: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6IjQ3MWVmYmQwLWY4NmUtNGQ3Yi04MTZhLTljY2E5ZDg5Zjk4YyJ9.-OtqDUDW5kE7dXRp4v6Pc5W87EhwRrApCL0tDL6AQCXrfUteWqXg-gf5qx17bdKO34f2KI17sJ16viatzxkEMA"

# 全局定时推送配置 - 启用
scheduled_push:
  enabled: true
  push_times: ["8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00"]
  title: "定时性能报告"
  include_host_monitoring: true
  include_app_monitoring: true
  
  # 告警信息保存配置
  alert_storage:
    enabled: true
    # 告警信息保存路径模板（按天存储）
    alert_log_path_template: "logs/%y/%m/%d/scheduled_push-%H%M.log"
    # 告警信息保存格式: json, text
    format: "json"
    # 告警信息保留天数（0表示永久保留）
    retention_days: 30

# 通用配置
dingtalk:
  webhook_url: "https://oapi.dingtalk.com/robot/send?access_token=bfd9580e7d49a959e986c74*******10b06ebad"
  secret: "SEC0b0f0a3d4f43d1d21d0a**********66d12fe97b22fa"
  at_mobiles: ["19******502"]

log:
  mode: both
  level: info
  output: logs/gwatch.log
  enable_rotation: true
  max_size: 100
  max_age: 30
  max_backups: 10

whiteProcessList:
  - "cursor"
  - "goland"
  - "bash"