// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"GWatch/internal/app/usecase"
	"GWatch/internal/domain/alert"
	"GWatch/internal/domain/collector"
	"GWatch/internal/domain/config"
	"GWatch/internal/domain/monitor"
	"GWatch/internal/domain/notifier"
	"GWatch/internal/domain/ticker"
	"GWatch/internal/entity"
	"GWatch/internal/infra/alert"
	"GWatch/internal/infra/collectors/external"
	"GWatch/internal/infra/collectors/host"
	ticker2 "GWatch/internal/infra/collectors/ticker"
	"GWatch/internal/infra/collectors/ticker/auth"
	"GWatch/internal/infra/config"
	"GWatch/internal/infra/monitor"
	"GWatch/internal/infra/notifier"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序的所有依赖
func InitializeApp() (*App, error) {
	provider, err := NewConfigProvider()
	if err != nil {
		return nil, err
	}
	config := NewConfig(provider)
	hostCollector := NewHostCollector()
	redisClient := NewRedisCollector(provider)
	httpCollector := NewHTTPCollector(provider)
	evaluator := NewEvaluator()
	basePolicy := NewBasePolicy()
	formatter := NewMarkdownFormatter()
	notifier := NewDingTalkNotifier(provider)
	baseMonitoringUseCase := NewBaseMonitoringUseCase(hostCollector, redisClient, httpCollector, evaluator, basePolicy, formatter, notifier)
	httpPolicy := NewHTTPPolicy()
	httpMonitoringUseCase := NewHTTPMonitoringUseCase(hostCollector, redisClient, httpCollector, evaluator, httpPolicy, formatter, notifier)
	coordinator := NewCoordinator(baseMonitoringUseCase, httpMonitoringUseCase, basePolicy, httpPolicy)
	tokenProvider := NewTokenProvider()
	tickerCollector := NewTickerCollector(tokenProvider)
	systemMetricsService := NewSystemMetricsService(hostCollector, redisClient, httpCollector)
	tickerFormatter := NewTickerMarkdownFormatter()
	tickerUseCase := NewTickerUseCase(tickerCollector, tokenProvider, systemMetricsService, evaluator, formatter, tickerFormatter, notifier)
	tickerScheduler := NewTickerScheduler(tickerUseCase)
	app := NewApp(config, coordinator, tickerScheduler)
	return app, nil
}

// wire.go:

// BasePolicy 基础告警策略类型别名
type BasePolicy *alertimpl.StatefulPolicy

// HTTPPolicy HTTP告警策略类型别名
type HTTPPolicy *alertimpl.StatefulPolicy

// BaseMonitoringUseCase 基础监控用例类型别名
type BaseMonitoringUseCase *usecase.MonitoringUseCase

// HTTPMonitoringUseCase HTTP监控用例类型别名
type HTTPMonitoringUseCase *usecase.MonitoringUseCase

// ProviderSet 定义所有基础设施提供者
var ProviderSet = wire.NewSet(

	NewConfigProvider,
	NewConfig,

	NewHostCollector,
	NewRedisCollector,
	NewHTTPCollector,
	NewTickerCollector,

	NewTokenProvider,

	NewEvaluator,
	NewMarkdownFormatter,
	NewTickerMarkdownFormatter,

	NewDingTalkNotifier,

	NewBasePolicy,
	NewHTTPPolicy,

	NewSystemMetricsService,

	NewBaseMonitoringUseCase,
	NewHTTPMonitoringUseCase,
)

// NewConfigProvider 创建配置提供者
func NewConfigProvider() (config.Provider, error) {
	return configimpl.NewYAMLProvider("config/config_test.yml")
}

// NewHostCollector 创建主机信息收集器
func NewHostCollector() collector.HostCollector {
	return host.New()
}

// NewRedisCollector 创建 Redis 收集器
func NewRedisCollector(provider config.Provider) usecase.RedisClient {
	return external.NewRedisCollector(provider)
}

// NewHTTPCollector 创建 HTTP 收集器
func NewHTTPCollector(provider config.Provider) collector.HTTPCollector {
	return external.NewHTTPCollector(provider)
}

// NewTickerCollector 创建 Ticker 收集器
func NewTickerCollector(tokenProvider ticker.TokenProvider) ticker.TickerCollector {
	return ticker2.NewTickerCollector(tokenProvider)
}

// NewTokenProvider 创建 Token 提供者
func NewTokenProvider() ticker.TokenProvider {
	return auth.NewTokenProvider()
}

// NewEvaluator 创建评估器
func NewEvaluator() monitor.Evaluator {
	return monitorimpl.NewSimpleEvaluator()
}

// NewMarkdownFormatter 创建 Markdown 格式化器
func NewMarkdownFormatter() alert.Formatter {
	return alertimpl.NewMarkdownFormatter()
}

// NewTickerMarkdownFormatter 创建 Ticker Markdown 格式化器
func NewTickerMarkdownFormatter() alert.TickerFormatter {
	return alertimpl.NewTickerMarkdownFormatter().(alert.TickerFormatter)
}

// NewDingTalkNotifier 创建钉钉通知器
func NewDingTalkNotifier(provider config.Provider) notifier.Notifier {
	return notifierimpl.NewDingTalkNotifier(provider)
}

// NewBasePolicy 创建基础告警策略
func NewBasePolicy() BasePolicy {
	return alertimpl.NewStatefulPolicy().(*alertimpl.StatefulPolicy)
}

// NewHTTPPolicy 创建 HTTP 告警策略
func NewHTTPPolicy() HTTPPolicy {
	return alertimpl.NewStatefulPolicy().(*alertimpl.StatefulPolicy)
}

// NewBaseMonitoringUseCase 创建基础监控用例
func NewBaseMonitoringUseCase(
	hostInfo collector.HostCollector,
	redisInfo usecase.RedisClient,
	httpInfo collector.HTTPCollector,
	evaluator monitor.Evaluator,
	policy BasePolicy,
	formatter alert.Formatter, notifier2 notifier.Notifier,

) BaseMonitoringUseCase {
	return usecase.NewMonitoringUseCase(
		hostInfo,
		redisInfo,
		httpInfo,
		evaluator,
		(*alertimpl.StatefulPolicy)(policy),
		formatter, notifier2,
	)
}

// NewHTTPMonitoringUseCase 创建HTTP监控用例
func NewHTTPMonitoringUseCase(
	hostInfo collector.HostCollector,
	redisInfo usecase.RedisClient,
	httpInfo collector.HTTPCollector,
	evaluator monitor.Evaluator,
	policy HTTPPolicy,
	formatter alert.Formatter, notifier2 notifier.Notifier,

) HTTPMonitoringUseCase {
	return usecase.NewMonitoringUseCase(
		hostInfo,
		redisInfo,
		httpInfo,
		evaluator,
		(*alertimpl.StatefulPolicy)(policy),
		formatter, notifier2,
	)
}

// NewSystemMetricsService 创建系统指标服务
func NewSystemMetricsService(
	hostInfo collector.HostCollector,
	redisInfo usecase.RedisClient,
	httpInfo collector.HTTPCollector,
) *usecase.SystemMetricsService {
	return usecase.NewSystemMetricsService(hostInfo, redisInfo, httpInfo)
}

// NewTickerUseCase 创建 Ticker 用例
func NewTickerUseCase(
	tickerInfo ticker.TickerCollector,
	tokenProvider ticker.TokenProvider,
	systemMetricsService *usecase.SystemMetricsService,
	evaluator monitor.Evaluator,
	formatter alert.Formatter,
	tickerFormatter alert.TickerFormatter, notifier2 notifier.Notifier,

) ticker.TickerUseCase {
	return usecase.NewTickerUseCase(
		tickerInfo,
		tokenProvider,
		systemMetricsService,
		evaluator,
		formatter,
		tickerFormatter, notifier2,
	)
}

// NewCoordinator 创建协调器
func NewCoordinator(
	runnerBase BaseMonitoringUseCase,
	runnerHTTP HTTPMonitoringUseCase,
	policyBase BasePolicy,
	policyHTTP HTTPPolicy,
) *usecase.Coordinator {
	return usecase.NewCoordinator(
		(*usecase.MonitoringUseCase)(runnerBase),
		(*usecase.MonitoringUseCase)(runnerHTTP),
		(*alertimpl.StatefulPolicy)(policyBase),
		(*alertimpl.StatefulPolicy)(policyHTTP),
	)
}

// NewTickerScheduler 创建 Ticker 调度器
func NewTickerScheduler(tickerRunner ticker.TickerUseCase) ticker.TickerScheduler {
	return usecase.NewTickerScheduler(tickerRunner)
}

// App 应用程序结构体，包含所有需要的组件
type App struct {
	Config          *entity.Config
	Coordinator     *usecase.Coordinator
	TickerScheduler ticker.TickerScheduler
}

// NewApp 创建应用程序实例
func NewApp(config2 *entity.Config,
	coordinator *usecase.Coordinator,
	tickerScheduler ticker.TickerScheduler,
) *App {
	return &App{
		Config:          config2,
		Coordinator:     coordinator,
		TickerScheduler: tickerScheduler,
	}
}

// NewConfig 从配置提供者获取配置
func NewConfig(provider config.Provider) *entity.Config {
	return provider.GetConfig()
}
